### ISSUE TITLE
Crashlog

### ISSUE THREAD

**Issue by ardissaps** [PTOM76/Materialisation#1]
https://paste.atlauncher.com/view/ea2acc02-f7ac-40a6-8b24-dade0ae71f22

**Comment by PTOM76** [comment]
Thank you for your report.
Fixed.
1.18.2: https://www.curseforge.com/minecraft/mc-mods/materialisation3/files/3891995
1.19: https://www.curseforge.com/minecraft/mc-mods/materialisation3/files/3892000
